server:
  port: 8383

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: doubao
    password: LfSK4cHRfc2yByfE
    url: jdbc:mysql://43.143.164.194:3306/doubao?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource

logging:
  level:
    root: info
    com.yovinchen.forum: info
